language: node_js
node_js:
  - '7.7.1'

before_install:
  - npm install -g webpack

script:
  - npm run build

deploy:
  provider: npm
  email: sandbox_JSUI@coveo.com
  skip_cleanup: true
  api_key:
    secure: ifevVBXLIZqoH1RD90fRv7ijQVqcUCbkFjppYMsyXApoCEGAz1wuXwpVvci8iRmp0UA7KvR7kHZSllMbxmuRVq5+K3mW7xXV4Y2tuX667IoSmGlqxqrDXsIQ4Xpj1NgU/hvgfPZ45rq20UPL7M19c7TXXzLG1iRsAfUyxh/5pRsryUNDRr9zRS33CDODpiAWowmZPetTNBA1i5ZNk9AuU4iFzqywjjxHNv0mVtQBhRJI7aeGnee5+bzTuMJD7CuegHsALwoZo1G17Y3emdK080xG5xNA/2sbRp86X6vUnREfEbrph5q5/wGp4B3mxvHW1W7FsE37vgFgiU32WFT72sThx6XOsdW7Ok3KPB66m7wxPUPtbD/VhEb0rTTkSJl+hVbcYqwtTsdD14OXQ/l29K9CcvhFwvQMGT81B6YDpP0jea5iBM1RoMD9ian9ehhn0MxiwySyG3YtcEwBWszZZsCQJBHgCweWGWspNLrV1jz/ayQSydVFNp7lzMUdTJVB9XoEwOtG2L9AZNHGfpPCmOmatEs7l6plpKC2OfbAuqUH0Mwe2cZ+xEFPNTSDVeKIYtyejoywl9Q2HR38s5uQ6+YPUciS8f8L+CsTDGOM8fb8AbmaLyQM+kT1eUh8G9rirAB07nWW8lYLGndX2zbPHFIL8jgM8Besa/rpQARCreU=
  on:
    tags: true